name: crack_310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24
  - h5py>=3.9.0
  - progressbar
  - imutils
  - scikit-image
  - ipython
  - scikit-learn
  - keras
  - graphviz
  - pip
  - pip:
      - tensorflow
      - keras-preprocessing
      - pydot
      - graphviz